### ISSUE TITLE
Ideas for major v2.0 release

### ISSUE THREAD

**Issue by Acconut** [tus/tus-js-client#167]
This issue is used to collect idea for a next major release of tus-js-client. Nothing is settled in stone, so feel free to express your ideas.

**Tasks before major release / with breaking changes**:
- [x] Remove `withCredentials` option
- [x] Remove `resume` option in favor of proper URL storage interface.
- [x] Add interfaces for `urlStorage` and `fileReader` options: https://github.com/tus/tus-js-client/commit/e8aea8d672e8d69ca2d34bf33061d69f74b64c04#diff-26d16a76eb2641c3108d9b4b67f9cb72R30
- [x] Add abstraction layer for different HTTP stacks (also allows easier mocks for testing)
- [x] Write fully new documentation
- [x] Document better approach to resuming uploads by using `Upload#start`
- [x] Enable retries by default
- [x] Add `onBeforeRequest` and `onAfterResponse` callbacks or similar to allow obtaining HTTP request/responses.
- [ ] Write blog post and release notes

**Tasks possible after major release / no breaking changes**:
- Restart upload if no progress events fired for a specific duration
- [x] Add support for splitting upload and uploading in parallel
- [x] Add more debugging output

**Dropped ideas**:
- ~~Drop UMD/AMD support and modernize compiling steps~~ (we will continue to use browserify and it provides the UMD bundle for free, so we will keep it)
- ~~Incorporate solution for large files in React Native (see https://github.com/tus/tus-js-client/issues/146)~~ We don't have enough experience with this approach and don't want to recommend this to end users without enough confidence

**Comment by thenano** [comment]
Hi @Acconut thanks so much for the work on this. I had been looking around a lot for good upload solutions for uploading large video files. I tried some chunk splitting parallel upload solutions (it seems that most video APIs support this instead of TUS) but couldn't find anything that actually worked on a js web client without a lot of fiddling. This one worked as expected out of the box!
So just to add some requests to the list:
- Not sure if your onAfterResponse solves this issue, but I use 2 different endpoints for the initial post and the subsequent patch requests. This is because I want to use an authenticated session to create a signed upload link (to a different server) and then later PATCH to that link. This actually works now apart from the authentication headers. So I would need to pass different headers between the POST/PATCH requests.
- Ability to send separate chunks in parallel

**Comment by Acconut** [comment]
> Not sure if your onAfterResponse solves this issue, but I use 2 different endpoints for the initial post and the subsequent patch requests. This is because I want to use an authenticated session to create a signed upload link (to a different server) and then later PATCH to that link. This actually works now apart from the authentication headers. So I would need to pass different headers between the POST/PATCH requests.

Yes, I think the onBeforeRequest callbacks should be exactly the solution you are talking about.

> Ability to send separate chunks in parallel

I will add it to the list but cannot make any promises about when it will implemented or available.

**Comment by thenano** [comment]
@Acconut thanks for the reply. Just to add a note saying I've managed to solve my separate POST/PATCH use case by using uploadUrl instead of enpoint and doing the initial post separately.

**Comment by fidelix** [comment]
Why remove `withCredentials`?

**Comment by Acconut** [comment]
> Why remove withCredentials?

I have never seen in been used in practice and it also does not fit properly in the Upload class anymore since we implemented the HTTP abstraction layer. If you want to enable `withCredentials`, you can use the new `onBeforeRequest` callback to modify outgoing requests.

> Also, I am very interested in this as well: Ability to send separate chunks in parallel

I added an option `parallelUploads` that specifies how many parallel upload requests should be sent. You can set it to 2 to upload the two file halves in parallel. The corresponding commit is https://github.com/tus/tus-js-client/commit/40233d3b77f2aad7453dda46b03420651b1eae6c.

**Comment by fidelix** [comment]
I use withCredentials currently. But no problem, I can modify the request onBeforeRequest.
And thanks for the parallelUploads addition!
